import { ImageResponse } from 'next/og'

// Route segment config — Next.js serves this as /opengraph-image
export const alt = 'fund24 — Fördermittel einfach finden'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

// Note: OG-images are generated by Next.js via the Satori renderer. We keep
// the layout in a subset of CSS that Satori supports (flexbox, no grid).
export default async function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          background: 'linear-gradient(135deg, #737688 0%, #637c74 100%)',
          display: 'flex',
          flexDirection: 'column',
          padding: 80,
          position: 'relative',
          fontFamily: 'sans-serif',
        }}
      >
        {/* Corner mark */}
        <div
          style={{
            fontSize: 18,
            letterSpacing: 6,
            textTransform: 'uppercase',
            color: 'rgba(255,255,255,0.5)',
            display: 'flex',
          }}
        >
          fund24.io
        </div>

        {/* Spacer */}
        <div style={{ flex: 1, display: 'flex' }} />

        {/* Hero */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
          <div
            style={{
              fontSize: 112,
              fontWeight: 700,
              color: '#ffffff',
              lineHeight: 1.05,
              letterSpacing: -3,
              display: 'flex',
            }}
          >
            Fördermittel
          </div>
          <div
            style={{
              fontSize: 112,
              fontWeight: 700,
              color: '#c9d1ff',
              lineHeight: 1.05,
              letterSpacing: -3,
              display: 'flex',
            }}
          >
            einfach finden.
          </div>

          <div
            style={{
              marginTop: 32,
              fontSize: 28,
              color: 'rgba(255,255,255,0.75)',
              lineHeight: 1.4,
              maxWidth: 900,
              display: 'flex',
            }}
          >
            Kostenloser KI-Fördercheck · 3.400+ Programme · Berater-Matching
          </div>
        </div>

        {/* Accent bar bottom-right */}
        <div
          style={{
            position: 'absolute',
            bottom: 80,
            right: 80,
            display: 'flex',
            gap: 8,
          }}
        >
          <div style={{ width: 60, height: 4, background: '#6575ad', display: 'flex' }} />
          <div style={{ width: 60, height: 4, background: '#069e7c', display: 'flex' }} />
        </div>
      </div>
    ),
    { ...size }
  )
}
